name: release
on:
  push:
    tags:
      - 'v*'   # tag like v0.1.0
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create a GitHub Release
    steps:
      - uses: actions/checkout@v4
      - name: Build (optional)
        run: |
          npm ci
          npm run build --if-present
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
